apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
    spec:
      containers:
        - name: front-despacho
          image: 355022228668.dkr.ecr.us-east-1.amazonaws.com/innovatech-front-despacho:latest # Will be updated by workflow
          ports:
            - containerPort: 80
          env:
            - name: VENTAS_IP
              value: "ventas-service"
            - name: DESPACHOS_IP
              value: "despachos-service"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
