name: Deploy Frontend

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Construir y Subir imagen a ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPO_URL: ${{ secrets.ECR_REPO_URL_FRONTEND }}
        IMAGE_TAG: latest
      run: |
        # Login a ECR de forma manual, como en tu ejercicio
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY
        
        docker build -t $ECR_REPO_URL:$IMAGE_TAG .
        docker push $ECR_REPO_URL:$IMAGE_TAG

    - name: Desplegar en EC2 via AWS SSM
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_FRONTEND_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":["aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}", "docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest", "docker stop front-despacho || true", "docker rm front-despacho || true", "docker run -d -p 80:80 --name front-despacho -e VENTAS_IP=${{ secrets.VENTAS_IP }} -e DESPACHOS_IP=${{ secrets.DESPACHOS_IP }} --restart unless-stopped ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"]}'
