name: Deploy Frontend

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Construir y Subir imagen a ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPO_URL: ${{ secrets.ECR_REPO_URL_FRONTEND }}
        IMAGE_TAG: latest
      run: |
        # Login a ECR de forma manual, como en tu ejercicio
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY
        
        docker build -t $ECR_REPO_URL:$IMAGE_TAG .
        docker push $ECR_REPO_URL:$IMAGE_TAG

    - name: Desplegar en EC2 via AWS SSM
      uses: aws-actions/aws-ssm-send-command@v1
      with:
        instance-ids: ${{ secrets.EC2_FRONTEND_INSTANCE_ID }}
        document-name: AWS-RunShellScript
        parameters: |
          commands:
            - "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}"
            - "docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
            - "mkdir -p /app/frontend && cd /app/frontend"
            - "cat << 'EOF' > docker-compose.yml"
            - "version: '3.8'"
            - "services:"
            - "  front-despacho:"
            - "    container_name: front-despacho"
            - "    image: ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
            - "    ports:"
            - "      - \"80:80\""
            - "    restart: unless-stopped"
            - "    networks:"
            - "      - innovatech-public-net"
            - "networks:"
            - "  innovatech-public-net:"
            - "    driver: bridge"
            - "EOF"
            - "docker compose down || true"
            - "docker compose up -d"
